name: SSH Connection Test

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the workflow

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest
    steps:
    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: 163.172.194.175 
        username: root
        key: ${{secrets.NEW_SERVER_SSH_KEY}}

        script: |
          echo "Successfully logged into the server."
